apiVersion: v2
name: external-dns
description: ExternalDNS synchronizes exposed Kubernetes Services and Ingresses with DNS providers.
type: application
version: 1.15.2
appVersion: 0.15.1
keywords:
  - kubernetes
  - externaldns
  - external-dns
  - dns
  - service
  - ingress
home: https://github.com/conduitxyz/external-dns/
icon: https://github.com/conduitxyz/external-dns/raw/master/docs/img/external-dns.png
sources:
  - https://github.com/conduitxyz/external-dns/
maintainers:
  - name: stevehipwell
    email: steve.hipwell@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Updated _ExternalDNS_ image repo to ghcr.io/conduitxyz/external-dns"
    - kind: added
      description: "Added `transportservers` resource to ClusterRole when specifying `f5-transportserver` or `f5-virtualserver` as a source."
    - kind: fixed
      description: "Fixed handling of non-string types in `serviceAccount.metadata.annotations` field."
    - kind: fixed
      description: "Fixed regression where `affinity.nodeAffinity` was being ignored."
